const abbreviations = {
    'Asian American Studies': 'AAS',
    'Agricultural and Biological Engineering': 'ABE',
    'Accountancy': 'ACCY',
    'Agricultural and Consumer Economics': 'ACE',
    'Agricultural, Consumer and Environmental Sciences': 'ACES',
    'Advertising': 'ADV',
    'Aerospace Engineering': 'AE',
    'Air Force Aerospace Studies': 'AFAS',
    'African American Studies': 'AFRO',
    'African Studies': 'AFST',
    'Agricultural Communications': 'AGCM',
    'Agricultural Education': 'AGED',
    'Applied Health Sciences Courses': 'AHS',
    'American Indian Studies': 'AIS',
    'Agricultural Leadership, Education, and Communications Program': 'ALEC',
    'Animal Sciences': 'ANSC',
    'Anthropology': 'ANTH',
    'Arabic': 'ARAB',
    'Architecture': 'ARCH',
    'Art': 'ART',
    'Art--Design': 'ARTD',
    'Art--Education': 'ARTE',
    'Art--Foundation': 'ARTF',
    'Art--History': 'ARTH',
    'Japan House': 'ARTJ',
    'Art--Studio': 'ARTS',
    'Actuarial Science and Risk Management': 'ASRM',
    'Asian Studies': 'ASST',
    'Astronomy': 'ASTR',
    'Atmospheric Sciences': 'ATMS',
    'Business Administration': 'BADM',
    'Basque': 'BASQ',
    'Brain and Cognitive Science': 'BCOG',
    'Bosnian-Croatian-Serbian': 'BCS',
    'Business Data and Innovation': 'BDI',
    'Biochemistry': 'BIOC',
    'Bioengineering': 'BIOE',
    'Biophysics': 'BIOP',
    'Biomedical Sciences and Engineering': 'BSE',
    'Business and Technical Writing': 'BTW',
    'Business': 'BUS',
    'Comparative Biosciences': 'CB',
    'Cell and Developmental Biology': 'CDB',
    'Civil and Environmental Engineering': 'CEE',
    'Chemical and Biomolecular Engineering': 'CHBE',
    'Chemistry': 'CHEM',
    'Chinese': 'CHIN',
    'Community Health': 'CHLH',
    'Campus Honors Program Courses': 'CHP',
    'Curriculum and Instruction': 'CI',
    'Committee on Inst Cooperation': 'CIC',
    'Classical Civilization': 'CLCV',
    'Clinical Sciences and Engineering': 'CLE',
    'Communication': 'CMN',
    'Crop Sciences': 'CPSC',
    'Computer Science': 'CS',
    'Computational Science and Engineering': 'CSE',
    'Creative Writing': 'CW',
    'Comparative and World Literature': 'CWL',
    'Czech': 'CZCH',
    'Dance': 'DANC',
    'Human-Centered Design and Design Thinking': 'DTX',
    'East Asian Language and Culture': 'EALC',
    'Electrical and Computer Engineering': 'ECE',
    'Economics': 'ECON',
    'Educational Practice': 'EDPR',
    'Education': 'EDUC',
    'English as an International Language': 'EIL',
    'Engineering': 'ENG',
    'English': 'ENGL',
    'Environmental Sustainability': 'ENSU',
    'Environmental Studies': 'ENVS',
    'Education Policy, Organization and Leadership': 'EPOL',
    'Educational Psychology': 'EPSY',
    'Education Research & Methods': 'ERAM',
    'Earth, Society, and Environment': 'ESE',
    'English as a Second Language': 'ESL',
    'Engineering Technology and Management for Agricultural Systems': 'ETMA',
    'European Union Studies': 'EURO',
    'Fine and Applied Arts': 'FAA',
    'Finance': 'FIN',
    'Foreign Language Teacher Education': 'FLTE',
    'French': 'FR',
    'Food Science and Human Nutrition': 'FSHN',
    'Graduate College': 'GC',
    'Geology': 'GEOL',
    'German': 'GER',
    'Geography & Geographic Information Science': 'GGIS',
    'Global Studies': 'GLBL',
    'Germanic': 'GMC',
    'Greek': 'GRK',
    'Modern Greek': 'GRKM',
    'General Studies': 'GS',
    'Game Studies and Design': 'GSD',
    "Gender and Women's Studies": 'GWS',
    'Human Development and Family Studies': 'HDFS',
    'Hebrew, Modern and Classical': 'HEBR',
    'History': 'HIST',
    'Hindi': 'HNDI',
    'Horticulture': 'HORT',
    'Health Technology': 'HT',
    'Humanities Courses': 'HUM',
    'Integrative Biology': 'IB',
    'Industrial Engineering': 'IE',
    'Interdisciplinary Health Sciences': 'IHLT',
    'Informatics': 'INFO',
    'Information Sciences': 'IS',
    'Italian': 'ITAL',
    'Japanese': 'JAPN',
    'Journalism': 'JOUR',
    'Jewish Studies': 'JS',
    'Kinesiology': 'KIN',
    'Korean': 'KOR',
    'Landscape Architecture': 'LA',
    'Liberal Arts and Sciences': 'LAS',
    'Latin American and Caribbean Studies': 'LAST',
    'Latin': 'LAT',
    'Law': 'LAW',
    'Less Commonly Taught Languages': 'LCTL',
    'Organizational and Community Leadership': 'LEAD',
    'Labor and Employment Relations': 'LER',
    'Linguistics': 'LING',
    'Latina/Latino Studies': 'LLS',
    'Media and Cinema Studies': 'MACS',
    'Mathematics': 'MATH',
    'Regular MBA Program Administration': 'MBA',
    'Molecular and Cell Biology': 'MCB',
    'Media': 'MDIA',
    'Medieval Studies': 'MDVL',
    'Mechanical Engineering': 'ME',
    'Microbiology': 'MICR',
    'Military Science': 'MILS',
    'Molecular and Integrative Physiology': 'MIP',
    'Materials Science and Engineering': 'MSE',
    'Music': 'MUS',
    'Music Lessons and Ensembles': 'MUSC',
    'Museum Studies': 'MUSE',
    'Neural Engineering': 'NE',
    'Neuroscience': 'NEUR',
    'Nuclear, Plasma, and Radiological Engineering': 'NPRE',
    'Natural Resources and Environmental Sciences': 'NRES',
    'Naval Science': 'NS',
    'Nutritional Sciences': 'NUTR',
    'Pathobiology': 'PATH',
    'Persian': 'PERS',
    'Philosophy': 'PHIL',
    'Physics': 'PHYS',
    'Plant Pathology': 'PLPA',
    'Polish': 'POL',
    'Portuguese': 'PORT',
    'Political Science': 'PS',
    "Professional Science Master's Program": 'PSM',
    'Psychology': 'PSYC',
    'Quechua': 'QUEC',
    'Russian, East European and Eurasian Studies': 'REES',
    'Rehabilitation Counseling': 'REHB',
    'Religion': 'REL',
    'Rhetoric and Composition': 'RHET',
    'Romance Linguistics': 'RMLG',
    'Recreation, Sport, and Tourism': 'RST',
    'Russian': 'RUSS',
    'South Asian and Middle Eastern Studies': 'SAME',
    'Strategic Brand Communication': 'SBC',
    'Scandinavian': 'SCAN',
    'Systems Engineering and Design': 'SE',
    'Speech and Hearing Science': 'SHS',
    'Slavic': 'SLAV',
    'Literatures, Cultures, and Linguistics': 'SLCL',
    'Sociology': 'SOC',
    'Social Work': 'SOCW',
    'Spanish': 'SPAN',
    'Special Education': 'SPED',
    'Statistics': 'STAT',
    'Swahili': 'SWAH',
    'Theoretical and Applied Mechanics': 'TAM',
    'Technology Entrepreneurship': 'TE',
    'Theatre': 'THEA',
    'Technology and Management Courses': 'TMGT',
    'Translation Studies': 'TRST',
    'Turkish': 'TURK',
    'Ukrainian': 'UKR',
    'Urban and Regional Planning': 'UP',
    'Veterinary Clinical Medicine': 'VCM',
    'Veterinary Medicine Courses': 'VM',
    'Wolof': 'WLOF',
    'Writing Studies': 'WRIT',
    'Yiddish': 'YDSH',
    'Zulu': 'ZULU'
};

module.exports = {abbreviations};
